SET session_replication_role = 'replica';

INSERT INTO factions(name) VALUES ('Beastmen');
INSERT INTO factions(name) VALUES ('Bretonnia');
INSERT INTO factions(name) VALUES ('Daemons of Chaos');
INSERT INTO factions(name) VALUES ('Dark Elves');
INSERT INTO factions(name) VALUES ('Dwarfs');
INSERT INTO factions(name) VALUES ('The Empire');
INSERT INTO factions(name) VALUES ('Grand Cathay');
INSERT INTO factions(name) VALUES ('Greenskins');
INSERT INTO factions(name) VALUES ('High Elves');
INSERT INTO factions(name) VALUES ('Khorne');
INSERT INTO factions(name) VALUES ('Kislev');
INSERT INTO factions(name) VALUES ('Lizardmen');
INSERT INTO factions(name) VALUES ('Norsca');
INSERT INTO factions(name) VALUES ('Nurgle');
INSERT INTO factions(name) VALUES ('Ogre Kingdoms');
INSERT INTO factions(name) VALUES ('Skaven');
INSERT INTO factions(name) VALUES ('Slaanesh');
INSERT INTO factions(name) VALUES ('Tomb Kings');
INSERT INTO factions(name) VALUES ('Tzeentch');
INSERT INTO factions(name) VALUES ('Vampire Coast');
INSERT INTO factions(name) VALUES ('Vampire Counts');
INSERT INTO factions(name) VALUES ('Warriors of Chaos');
INSERT INTO factions(name) VALUES ('Wood Elves');

INSERT INTO avatars(id, url) VALUES (0, 'null');
INSERT INTO avatars(id, url) VALUES (1, 'null1');

INSERT INTO units(name, cost, avatar_id) VALUES ('Boyar', 1550, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Ice Witch (Ice)', 2062, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Ice Witch (Tempest)', 2062, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Kotaltyn', 2100, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Tzarina Katarin', 2312, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Patriarch', 1500, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Frost Maiden (Ice)', 1712, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Frost Maiden (Tempest)', 1712, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Armoured Kossars', 650, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Armoured Kossars (Great Weapons)', 700, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Tzar Guard', 1000, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Tzar Guard (Great Weapons)', 1100, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Kossars', 450, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Kossars (Spears)', 500, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Streltsi', 850, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Ice Guard (Swords)', 1100, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Ice Guard (Glaives)', 1150, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Kossovite Dervishes', 450, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Winged Lancers', 850, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Gryphon Legion', 1150, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('War Bear Riders', 1600, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Horse Archers', 600, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Light War Sleds', 1100, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Heavy War Sleds', 1350, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Snow Leopard', 650, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Elemental Bear', 1900, 1);
INSERT INTO units(name, cost, avatar_id) VALUES ('Little Grom', 650, 1);

INSERT INTO units_factions(unit_id, faction_id) VALUES (0,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (1,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (2,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (3,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (4,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (5,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (6,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (7,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (8,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (9,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (10,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (11,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (12,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (13,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (14,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (15,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (16,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (17,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (18,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (19,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (20,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (21,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (22,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (23,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (24,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (25,10);
INSERT INTO units_factions(unit_id, faction_id) VALUES (26,10);

INSERT INTO lords(unit_id) VALUES (0);
INSERT INTO lords(unit_id) VALUES (1);
INSERT INTO lords(unit_id) VALUES (2);
INSERT INTO lords(unit_id) VALUES (3);
INSERT INTO lords(unit_id) VALUES (4);

INSERT INTO heroes(unit_id) VALUES (5);
INSERT INTO heroes(unit_id) VALUES (6);
INSERT INTO heroes(unit_id) VALUES (7);

SET session_replication_role = 'origin';
