version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tw-army-builder
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/tw-army-builder -schemas=public -user=admin
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  server:
    profiles: [ "dev" ]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      DbConnectionString: "Server=db,5432;Database=tw-army-builder;User Id=admin;Password=password;"
    volumes:
      - ./server:/app
    ports:
      - 5001:5001
      - 5000:5000
    depends_on:
      - flyway
  ui:
    profiles: [ "dev" ]
    build:
      context: ./ui
      dockerfile: Dockerfile.local
    environment:
      REACT_APP_API_URL: "http://localhost:5000/api"
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000
    depends_on:
      - server
volumes:
  db: