/*
 * TotalArmyBuilder.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.5.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";


const BASE_URL = "http://localhost:5000";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/Compositions/{id}/units", () => {
        let id = '2';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Compositions/${id}/units`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Units/heroes", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/Units/heroes`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Compositions/{id}", () => {
        let id = '1';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Compositions/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/Compositions/${id}`;
            let body = {"name": "Ice Guard Box", "battleType": "Land Battles", "factionId": 7, "avatarId": 1, "budget": 8000, "wins": 0, "losses": 0, "units": null};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 204
            });
        }
    });

    group("/api/Compositions", () => {
        // Request No. 1
        {
            let url = BASE_URL + `/api/Compositions/`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/Compositions`;
            let body = {"name": "Ice Guard Box2", "battleType": "Land Battles", "factionId": 7, "avatarId": 1, "budget": 8000, "wins": 0, "losses": 0, "units": null};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 201
            });
        }
    });

    group("/api/Factions/{id}", () => {
        let id = '1';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Factions/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Units/{id}", () => {
        let id = '1';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Units/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Factions", () => {
        let name = 'Beastmen';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Factions?name=${name}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Authentication", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/Authentication`;
            let body = {"email": "johndoe@example.com", "password": "$2a$11$78nO9BRsnqm6f6U0VngPLecM9yJLX02Vfqn3OO0xIGVpLwd13ZtRS"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Units/lords", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/Units/lords`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Factions/{id}/units", () => {
        let id = '7';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Factions/${id}/units`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Units/{id}/factions", () => {
        let id = '1';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Units/${id}/factions`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Accounts", () => {
        let email = 'johndoe@example.com';
        let username = null;

        // Request No. 1
        {
            let url = BASE_URL + `/api/Accounts?username=${username}&email=${email}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/Accounts`;
            let body = {"username": "JohnDoe2", "email": "johndoe2@example.com", "password": "newpassword123"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 201
            });
        }
    });

    group("/api/Accounts/{id}/compositions", () => {
        let id = '1';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Accounts/${id}/compositions`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/Accounts/{id}", () => {
        let id = '1';

        // Request No. 1
        {
            let url = BASE_URL + `/api/Accounts/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/Accounts/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"username": "JohnDoe", "email": "johndoe@example.com", "password": "Password123"};
            let params = {headers: {"Content-Type": "application/json-patch+json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 204
            });
        }
    });

    group("/api/Units", () => {
        let cost = 1000;
        let name = null;

        // Request No. 1
        {
            let url = BASE_URL + `/api/Units?name=${name}&cost=${cost}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

}
