AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Cloud Template to create resources required to deploy Some Application. For our small db application we will be needing AWS Lightsail container, S3 and RDS DB Services.

Parameters:
  DBPassword:
    Type: String
    Description: Password for the DB admin account.
    Default: Password123

Resources:
  Database:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: totalarmybuilder
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      PubliclyAccessible: true
      Engine: postgres
      EngineVersion: "12.9"
      MasterUsername: postgres
      MasterUserPassword: !Ref DBPassword

  APIContainer:
    Type: AWS::Lightsail::Container
    Properties:
      IsDisabled: false
      Power: micro
      Scale: 1
      ServiceName: totalarmybuilder-api-container

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref RootDomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
